### PR TITLE
Add historian-excluded-commands

### PR DESCRIPTION
**Pull request by raxod502**
So, removing `swiper`-related history from my `.historian` saved about
1500 lines and almost 0.5s of Emacs shutdown time.

### CODE REVIEW

**Comment by PythonNut** [comment]
Okay, so do you really use `swiper` that much?

**Comment by raxod502** [comment]
The problem seems to be that `swiper` saves a *ton* of additional information about the match as metadata, which `historian` just dumps into the hash table as well. Plus, some lines are really long.

**Comment by PythonNut** [comment]
That's what I thought. In certain cases, text properties can bloat the file by an enormous factor. I'm considering adding a case where we simply strip them out.

**Comment by raxod502** [comment]
I can't ​really think of a reason why we would ever want to keep text
properties. Would they ever be a relevant factor in sort order?

**Comment by PythonNut** [comment]
I can't think of a case where they would be.

**Comment by raxod502** [comment]
Sounds like ​it should be pretty simple, just call set-text-properties or
somesuch on the value being added.

**Comment by PythonNut** [comment]
My usual way is `substring-no-properties`.

**Pull request merged**
